#!/usr/bin/env bash

#/ command: beeroclock:beer: "Beer me"
#/ usage: rerun beeroclock:beer [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "beer" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

cat "$RERUN_MODULE_DIR/lib/server/beer.asciiart"

# Done. Exit with last command exit status.
exit $?

