language: c
compiler: gcc
if: tag IS blank
script: /usr/lib/x86_64-linux-gnu/rerun/travis-ci-modules.sh
notifications:
  irc:
  - irc.freenode.org#rerun
addons:
  apt:
    packages:
    - markdown
    - fakeroot
    - build-essential
    - devscripts
    - autoconf
    - automake
    - dh-make
    - libfile-fcntllock-perl
    - rpm
    - xmlstarlet
    - jq
    - wget
    - zip
    - rerun
    sources:
    - sourceline: deb https://dl.bintray.com/rerun/rerun-deb /
env:
  global:
  - BINTRAY_USER=ahonor
  - BINTRAY_ORG=rerun
  - secure: eq5gO+7xshP/tMnctxlqdP3QH6abCUyvI2ML4KHcgvymlNumpcm/Zy1x+7QHP14sOhozL70b869xnXsiMWN+rlXEZysBSAfUdswH++ARZLPhlkm+7hqzRzdSEYWHsT6cVq2RXBz/TdCxEFZj19I6jw7iJnxbsLfpKp/ujtHQqX30lT0DNVsxH6tjO+0fcUg7K1igki436sZ0PjVd8EVToiVnz/GBX6wzZ+TfYXNdeNo3+4Ppb+wlvhSCmVt/Aj4EHxGWZ0JC1MCcoJnjT8SU/FULfCcprwR+17Wgmy/4tSkSTqLbwrOUwpwaubkqRm+Jy5Ji+85HGjFnxSF8xGd+/oY46yQjrF6HXpjjk6qukL+Jybm9lvr0PlIVM/ocOlTytjjDr8aU0+TORNIAtNrpWOQHdmHd0dexTvCuHYF8hu5ItxipgiBCvqvYdqyGuL+BgRA7lAVX6pagY08KaD9xSH3RWIFDEFvVmR+JBVY1ElpGkuVgsEukKa8rpl3P2p0G4Z50r3U+5Ew0xT6N0p6zLzjGbHCVAHlPqxWXqNyJ/VuImaL8svEsgVieAHNpUvcYBGyrbLnYL6bkSSEkeRhQ0kzMLOqF1GmHHS0FUv9oAMltiot6qE9S5R/lL8cX7/OC9lJwCMtDWyY7Ca++/m6w5S4yvubT9UfM9+sAyKXwfqI=
