language: c
compiler: gcc
if: tag IS blank
script: "/usr/lib/x86_64-linux-gnu/rerun/travis-ci-modules.sh"
notifications:
  irc:
  - irc.freenode.org#rerun
addons:
  apt:
    packages:
    - markdown
    - fakeroot
    - build-essential
    - devscripts
    - autoconf
    - automake
    - dh-make
    - libfile-fcntllock-perl
    - rpm
    - xmlstarlet
    - jq
    - wget
    - zip
    - rerun
    - rerun-bintray
    sources:
    - sourceline: deb https://dl.bintray.com/rerun/rerun-deb /
env:
  global:
  - BINTRAY_USER=ahonor
  - BINTRAY_ORG=rerun
  - secure: eq5gO+7xshP/tMnctxlqdP3QH6abCUyvI2ML4KHcgvymlNumpcm/Zy1x+7QHP14sOhozL70b869xnXsiMWN+rlXEZysBSAfUdswH++ARZLPhlkm+7hqzRzdSEYWHsT6cVq2RXBz/TdCxEFZj19I6jw7iJnxbsLfpKp/ujtHQqX30lT0DNVsxH6tjO+0fcUg7K1igki436sZ0PjVd8EVToiVnz/GBX6wzZ+TfYXNdeNo3+4Ppb+wlvhSCmVt/Aj4EHxGWZ0JC1MCcoJnjT8SU/FULfCcprwR+17Wgmy/4tSkSTqLbwrOUwpwaubkqRm+Jy5Ji+85HGjFnxSF8xGd+/oY46yQjrF6HXpjjk6qukL+Jybm9lvr0PlIVM/ocOlTytjjDr8aU0+TORNIAtNrpWOQHdmHd0dexTvCuHYF8hu5ItxipgiBCvqvYdqyGuL+BgRA7lAVX6pagY08KaD9xSH3RWIFDEFvVmR+JBVY1ElpGkuVgsEukKa8rpl3P2p0G4Z50r3U+5Ew0xT6N0p6zLzjGbHCVAHlPqxWXqNyJ/VuImaL8svEsgVieAHNpUvcYBGyrbLnYL6bkSSEkeRhQ0kzMLOqF1GmHHS0FUv9oAMltiot6qE9S5R/lL8cX7/OC9lJwCMtDWyY7Ca++/m6w5S4yvubT9UfM9+sAyKXwfqI=
  - secure: lBuVg4SnXHDB3CAMF/5wvLvvD6NXVPYFkFhdLeraHaujIVuVhQTdielXPiKKeeMbBe40GpQX/rmWmwJoM99/71eB306JHUI8rem9q/Dc9RCcr8WYXaQ4LcfaxrvsyHya/kswuNzWRNsdSOBnMzMo7QxKWOyghuArQ9ncpwLpGv/GTf2k3UuD5BToBNS3heZi+0nxwQDOy29sjFFKOmR2SBim5dUp3aZ02IKkGYVoF/sUZNF+k5Y7KKM+APMss9shVP1ORK1faFGgovqv8NqGaPJEewJ9QvvpvWF2wjmdXbDhTkyewdPE7xXkl83mLQn4M1j4EwA3tpO1268+zA/aiw4eXanTjsNJp0u306EhMl6ZNZpdXVzUzfpHb+6dGho4tBXkJRNizfJp2xQUsRjo1R8ZDeZ9bO/39JiE//IOIaMy3L3QWTGmR4zIJ+UAuEbwEdUzhXa/cptP6fIJThwcBzv/LlEaKz/LXjDOtTX2okyazAhcCSHQt7fwvJOsRRfJCo4NA1/wrh/swaZXAJ/Mgxzm6glyrcOHV1M6Rl9EZk854jDbKWd4EOo6BJ4GXEVxyc/11cUjcWrasTPVC+LZs8o4PHQapShZsHC0mpja5dYytGn5WYokFVkVXKUwgFOFh2lYe4eoQt0N3Bcdha3DAKZ+6J0ziZNWkmMhVnMt6zU=    
sudo: required
services:
  - docker
before_install:
  - docker build -t beeroclock .  
