#!/usr/bin/env bash

#/ command: beeroclock:serve: "Run the beeroclock service"
#/ usage: rerun beeroclock:serve [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "server" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------


"$RERUN_MODULE_DIR/lib/server/service.sh"


# Done. Exit with last command exit status.
exit $?

